pentalog_blog_homepage:
    pattern:  /{page}
    defaults: { _controller: PentalogBlogBundle:Blog:index, page: 1 }
    requirements:
        page: \d*
    
pentalog_blog_view:
    pattern: /article/{id}
    defaults: { _controller: PentalogBlogBundle:Blog:view }
    
pentalog_blog_view_slug:
    pattern: /article/{year}/{slug}.{format}
    defaults: { _controller: PentalogBlogBundle:Blog:viewSlug, format: html }
    requirements:
        year: \d{4}
        format: html|xml
    
pentalog_blog_add:
    pattern: /add
    defaults: { _controller: PentalogBlogBundle:Blog:add }
    
pentalog_blog_edit:
    pattern: /edit/{id}
    defaults: { _controller: PentalogBlogBundle:Blog:edit }
    requirements:
        id: \d*
        
pentalog_blog_delete:
    pattern: /delete/{id}
    defaults: { _controller: PentalogBlogBundle:Blog:delete }
    requirements:
        id: \d*
