parameters:
#    pentalog_blog.example.class: Pentalog\BlogBundle\Example

services:
#    pentalog_blog.example:
#        class: %pentalog_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    pentalog_blog.antispam:
        class: Pentalog\BlogBundle\Antispam\PentalogAntispam
        arguments: [@mailer, %locale%, 3]
    pentalog_blog.validator.antiflood:
        class: Pentalog\BlogBundle\Validator\AntiFloodValidator
        arguments: [@request, @doctrine.orm.entity_manager]
        scope: request
        tags:
            - { name: validator.constraint_validator, alias: pentalog_blog_antiflood }
