parameters:
#    pentalog_blog.example.class: Pentalog\BlogBundle\Example

services:
#    pentalog_blog.example:
#        class: %pentalog_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    pentalog_blog.antispam:
        class: Pentalog\BlogBundle\Antispam\PentalogAntispam
        arguments: [@mailer, 3]
        tags:
            -  { name: twig.extension }
        calls:
            - [ setLocale, [ %locale% ] ]
    pentalog_blog.validator.antiflood:
        class: Pentalog\BlogBundle\Validator\AntiFloodValidator
        arguments: [@request, @doctrine.orm.entity_manager]
        scope: request
        tags:
            - { name: validator.constraint_validator, alias: pentalog_blog_antiflood }
    pentalog_ckeditor:
        class: Pentalog\BlogBundle\Form\Type\Ckeditor
        tags:
            - { name: form.type, alias: ckeditor }
#    pentalog_blog.beta_listener:
#        class: Pentalog\BlogBundle\Beta\BetaListener
#        arguments: ["2014-08-19"]
#        tags:
#            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
#            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
    pentalog_blog.bigbrother:
        class: Pentalog\BlogBundle\Bigbrother\CensureListener
        arguments: [[1, 2, 3], @mailer]
        tags:
            - { name: kernel.event_listener, event: pentalog_blog.bigbrother.post_message, method: onMessagePost }
